### ISSUE TITLE
indent ecto keyword queries

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/vim-elixir#237]
I think we should indent Ecto queries as in the following example from the docs: https://hexdocs.pm/ecto/Ecto.Query.html#having/3-keywords-example

Currently this expected indentation:

```ex
defmodule New do
  def do_query do
    from user in Users,
      select: user.name,
      join: signup in Signups, where: user.id == signup.user_id
  end
end
```

Will indent as:

```ex
defmodule New do
  def do_query do
    from user in Users,
    select: user.name,
    join: signup in Signups, where: user.id == signup.user_id
  end
end
```

**Comment by kassio** [comment]
I don't know if I agree, since the `from` is a function, and I think all the parameters of a function must be indented one extra level if they are in the following likes. The documentation itself has some examples that follow what I'm saying:

<img width="1194" alt="ecto_query_ _ecto_v2_1_1" src="https://cloud.githubusercontent.com/assets/120483/21651719/a49938fa-d2a1-11e6-89ca-ab98c691a160.png">
> https://hexdocs.pm/ecto/Ecto.Query.html

**Comment by jbodah** [comment]
I think we're saying the same thing, right? I may have trickily switched up the actual/expected ordering here
